# Generated by make-data-tests on 2012/04/11 04:16:08 +0000

#
# ABINIT Test Suite support for the "configure" script
#

#
# IMPORTANT NOTE
#
# This file has been automatically generated by the make-data-tests
# script. If you try to edit it, your changes will systematically be
# overwritten.
#



# ABI_TESTS_INIT()
# --------------
#
# Defines whether the Abinit Documentation may be built along with the package.
#
AC_DEFUN([ABI_TESTS_INIT],[
  dnl Init
  abi_tests_mode="subsystem"
  AC_CONFIG_SUBDIRS([tests])


  case "${abi_tests_mode}" in
    data)
      AC_MSG_NOTICE([the Abinit Documentation will never be built])
      ;;
    subsystem)
      AC_MSG_NOTICE([the Abinit Documentation may be built upon request])
      ;;
  esac

  AM_CONDITIONAL([DO_BUILD_TESTS],[test "${enable_tests_build}" = "yes"])
]) # ABI_TESTS_INIT
