/* This file has been automatically generated, do not modify. */
#ifndef AB6_INVARS_C_H
#define AB6_INVARS_C_H

static Ab6InvarsTypes ab6_invars_types[] = {
           _INT_SCALAR    ,  /* symchi          */
           _DOUBLE_SCALAR ,  /* gwencomp        */
           _DOUBLE_SCALAR ,  /* slabwsrad       */
           _INT_SCALAR    ,  /* rfstrs          */
           _INT_SCALAR    ,  /* exchn2n3d       */
           _INT_SCALAR    ,  /* nstep           */
           _INT_SCALAR    ,  /* wvl_nprccg      */
           _INT_SCALAR    ,  /* gwgamma         */
           _DOUBLE_SCALAR ,  /* gw_toldfeig     */
           _INT_SCALAR    ,  /* nsheps          */
           _DOUBLE_SCALAR ,  /* tolmxf          */
           _DOUBLE_SCALAR ,  /* charge          */
           _INT_SCALAR    ,  /* prt1dm          */
           _INT_SCALAR    ,  /* prepanl         */
           _INT_SCALAR    ,  /* nspinor         */
           _INT_SCALAR    ,  /* ndtset          */
           _INT_SCALAR    ,  /* usepawu         */
           _INT_SCALAR    ,  /* mpw             */
           _INT_SCALAR    ,  /* pawcross        */
           _INT_SCALAR    ,  /* occopt          */
           _DOUBLE_SCALAR ,  /* postoldff       */
           _DOUBLE_SCALAR ,  /* postoldfe       */
           _DOUBLE_ARRAY  ,  /* boxcenter       */
           _DOUBLE_SCALAR ,  /* bxctmindg       */
           _DOUBLE_ARRAY  ,  /* qptdm           */
           _INT_SCALAR    ,  /* td_mexcit       */
           _INT_SCALAR    ,  /* nctime          */
           _INT_SCALAR    ,  /* frzfermi        */
           _INT_SCALAR    ,  /* rfphon          */
           _INT_SCALAR    ,  /* prtden          */
           _INT_SCALAR    ,  /* gwpara          */
           _INT_SCALAR    ,  /* npfft           */
           _INT_SCALAR    ,  /* irdbsreso       */
           _INT_SCALAR    ,  /* recptrott       */
           _INT_ARRAY     ,  /* typat           */
           _INT_SCALAR    ,  /* jdtset          */
           _INT_SCALAR    ,  /* bs_haydock_niter */
           _INT_SCALAR    ,  /* pawprtden       */
           _INT_SCALAR    ,  /* use_gpu_cuda    */
           _INT_ARRAY     ,  /* algalch         */
           _INT_SCALAR    ,  /* prepscphon      */
           _INT_ARRAY     ,  /* kptrlatt        */
           _INT_SCALAR    ,  /* bs_algorithm    */
           _INT_SCALAR    ,  /* gwmem           */
           _INT_ARRAY     ,  /* nloalg          */
           _INT_SCALAR    ,  /* npkpt           */
           _INT_SCALAR    ,  /* iextrapwf       */
           _INT_SCALAR    ,  /* usekden         */
           _DOUBLE_ARRAY  ,  /* xred_orig       */
           _DOUBLE_ARRAY  ,  /* kptns           */
           _INT_SCALAR    ,  /* nberry          */
           _INT_SCALAR    ,  /* chksymbreak     */
           _DOUBLE_SCALAR ,  /* freqremin       */
           _INT_SCALAR    ,  /* usewvl          */
           _INT_SCALAR    ,  /* useexexch       */
           _DOUBLE_SCALAR ,  /* exchmix         */
           _DOUBLE_ARRAY  ,  /* bs_freq_mesh    */
           _INT_SCALAR    ,  /* tfkinfunc       */
           _DOUBLE_ARRAY  ,  /* ptcharge        */
           _DOUBLE_SCALAR ,  /* kptnrm          */
           _INT_SCALAR    ,  /* irdbseig        */
           _DOUBLE_SCALAR ,  /* slabzbeg        */
           _INT_SCALAR    ,  /* ionmov          */
           _DOUBLE_SCALAR ,  /* vis             */
           _DOUBLE_ARRAY  ,  /* cd_imfrqs       */
           _DOUBLE_SCALAR ,  /* userre          */
           _INT_SCALAR    ,  /* npwwfn          */
           _INT_SCALAR    ,  /* mffmem          */
           _INT_SCALAR    ,  /* bs_exchange_term */
           _INT_SCALAR    ,  /* mk1mem          */
           _INT_SCALAR    ,  /* nfreqsus        */
           _INT_SCALAR    ,  /* prtkpt          */
           _INT_SCALAR    ,  /* prtcs           */
           _INT_SCALAR    ,  /* imgmov          */
           _INT_SCALAR    ,  /* npspinor        */
           _DOUBLE_ARRAY  ,  /* qmass           */
           _DOUBLE_ARRAY  ,  /* gw_qlwl         */
           _DOUBLE_SCALAR ,  /* ecutsigx        */
           _INT_SCALAR    ,  /* ndyson          */
           _DOUBLE_SCALAR ,  /* wvl_hgrid       */
           _INT_SCALAR    ,  /* userec          */
           _INT_SCALAR    ,  /* getxcart        */
           _INT_SCALAR    ,  /* spmeth          */
           _INT_SCALAR    ,  /* mkmem           */
           _INT_ARRAY     ,  /* qprtrb          */
           _INT_SCALAR    ,  /* chkgwcomp       */
           _INT_SCALAR    ,  /* getden          */
           _DOUBLE_SCALAR ,  /* recefermi       */
           _INT_SCALAR    ,  /* prtgeo          */
           _INT_SCALAR    ,  /* prtfc           */
           _DOUBLE_SCALAR ,  /* vacwidth        */
           _DOUBLE_ARRAY  ,  /* mixalch         */
           _INT_SCALAR    ,  /* usedmatpu       */
           _DOUBLE_SCALAR ,  /* td_maxene       */
           _INT_SCALAR    ,  /* paral_kgb       */
           _INT_SCALAR    ,  /* get1wf          */
           _INT_SCALAR    ,  /* irdden          */
           _DOUBLE_SCALAR ,  /* zcut            */
           _INT_SCALAR    ,  /* getbseig        */
           _INT_SCALAR    ,  /* getxred         */
           _DOUBLE_SCALAR ,  /* bmass           */
           _INT_SCALAR    ,  /* w90prtunk       */
           _DOUBLE_ARRAY  ,  /* ratsph          */
           _INT_SCALAR    ,  /* intexact        */
           _INT_SCALAR    ,  /* useylm          */
           _INT_SCALAR    ,  /* macro_uj        */
           _INT_SCALAR    ,  /* dmft_rslf       */
           _DOUBLE_SCALAR ,  /* freqsuslo       */
           _INT_SCALAR    ,  /* npimage         */
           _INT_SCALAR    ,  /* getcell         */
           _INT_SCALAR    ,  /* maxnsym         */
           _DOUBLE_SCALAR ,  /* tolsym          */
           _DOUBLE_SCALAR ,  /* rectolden       */
           _INT_SCALAR    ,  /* kssform         */
           _DOUBLE_SCALAR ,  /* userrd          */
           _DOUBLE_SCALAR ,  /* userra          */
           _DOUBLE_SCALAR ,  /* userrc          */
           _DOUBLE_SCALAR ,  /* userrb          */
           _INT_SCALAR    ,  /* berrystep       */
           _DOUBLE_SCALAR ,  /* dmft_mxsf       */
           _INT_SCALAR    ,  /* wfoptalg        */
           _DOUBLE_ARRAY  ,  /* vcutgeo         */
           _INT_SCALAR    ,  /* rf1elfd         */
           _DOUBLE_ARRAY  ,  /* tnons           */
           _INT_SCALAR    ,  /* irdwfk          */
           _INT_SCALAR    ,  /* ird1den         */
           _INT_SCALAR    ,  /* ntimimage       */
           _INT_SCALAR    ,  /* pawlcutd        */
           _INT_ARRAY     ,  /* nband           */
           _INT_SCALAR    ,  /* prteig          */
           _DOUBLE_SCALAR ,  /* pawujv          */
           _INT_SCALAR    ,  /* enunit          */
           _INT_SCALAR    ,  /* vdw_nfrag       */
           _INT_SCALAR    ,  /* prtnest         */
           _INT_SCALAR    ,  /* irdwfq          */
           _INT_SCALAR    ,  /* pawstgylm       */
           _INT_SCALAR    ,  /* iprcel          */
           _INT_ARRAY     ,  /* iatfix          */
           _INT_SCALAR    ,  /* ldgapp          */
           _INT_SCALAR    ,  /* restartxf       */
           _INT_SCALAR    ,  /* irdddk          */
           _INT_ARRAY     ,  /* dynimage        */
           _INT_SCALAR    ,  /* spgroup         */
           _INT_SCALAR    ,  /* npwsigx         */
           _INT_SCALAR    ,  /* nomegasi        */
           _INT_SCALAR    ,  /* nomegasf        */
           _INT_ARRAY     ,  /* iatsph          */
           _INT_SCALAR    ,  /* nline           */
           _INT_SCALAR    ,  /* gw_eet_nband    */
           _DOUBLE_ARRAY  ,  /* kpt             */
           _INT_ARRAY     ,  /* bdberry         */
           _INT_SCALAR    ,  /* rfmeth          */
           _INT_SCALAR    ,  /* useria          */
           _INT_SCALAR    ,  /* nfreqsp         */
           _INT_SCALAR    ,  /* useric          */
           _INT_SCALAR    ,  /* userid          */
           _INT_SCALAR    ,  /* userie          */
           _DOUBLE_ARRAY  ,  /* gw_freqsp       */
           _INT_SCALAR    ,  /* random_atpos    */
           _INT_SCALAR    ,  /* ntypalch        */
           _INT_SCALAR    ,  /* localrdwf       */
           _INT_SCALAR    ,  /* prtdosm         */
           _INT_SCALAR    ,  /* nimage          */
           _DOUBLE_ARRAY  ,  /* mdtemp          */
           _DOUBLE_SCALAR ,  /* cd_halfway_freq */
           _DOUBLE_SCALAR ,  /* diemix          */
           _DOUBLE_ARRAY  ,  /* densty          */
           _DOUBLE_SCALAR ,  /* posocc          */
           _INT_SCALAR    ,  /* irdkss          */
           _INT_SCALAR    ,  /* rectesteg       */
           _INT_SCALAR    ,  /* ntypat          */
           _INT_SCALAR    ,  /* icoulomb        */
           _DOUBLE_ARRAY  ,  /* corecs          */
           _INT_SCALAR    ,  /* ikhxc           */
           _INT_SCALAR    ,  /* prtxml          */
           _INT_SCALAR    ,  /* pawxcdev        */
           _INT_SCALAR    ,  /* inclvkb         */
           _INT_SCALAR    ,  /* ndynimage       */
           _DOUBLE_SCALAR ,  /* ecutsm          */
           _DOUBLE_SCALAR ,  /* freqremax       */
           _INT_SCALAR    ,  /* nbdbuf          */
           _INT_SCALAR    ,  /* natpawu         */
           _DOUBLE_SCALAR ,  /* dielam          */
           _INT_SCALAR    ,  /* rf1phon         */
           _INT_SCALAR    ,  /* pawntheta       */
           _INT_SCALAR    ,  /* bdeigrf         */
           _INT_SCALAR    ,  /* pawujat         */
           _INT_SCALAR    ,  /* ixc             */
           _INT_SCALAR    ,  /* delayperm       */
           _INT_SCALAR    ,  /* nscforder       */
           _DOUBLE_SCALAR ,  /* pawovlp         */
           _DOUBLE_ARRAY  ,  /* atvshift        */
           _INT_SCALAR    ,  /* prtpmp          */
           _DOUBLE_SCALAR ,  /* cpus            */
           _DOUBLE_SCALAR ,  /* ecuteps         */
           _INT_SCALAR    ,  /* rf3elfd         */
           _INT_SCALAR    ,  /* suskxcrs        */
           _INT_SCALAR    ,  /* iprcfc          */
           _INT_SCALAR    ,  /* usexcnhat       */
           _INT_SCALAR    ,  /* irdbscoup       */
           _DOUBLE_ARRAY  ,  /* genafm          */
           _DOUBLE_SCALAR ,  /* scphon_temp     */
           _INT_ARRAY     ,  /* ngfftdg         */
           _INT_ARRAY     ,  /* rf3atpol        */
           _INT_SCALAR    ,  /* dmft_solv       */
           _INT_SCALAR    ,  /* prepgkk         */
           _INT_SCALAR    ,  /* gw_reconst_scr  */
           _DOUBLE_ARRAY  ,  /* rprimd_orig     */
           _INT_SCALAR    ,  /* prtvxc          */
           _INT_SCALAR    ,  /* nfftdg          */
           _INT_SCALAR    ,  /* paral_rf        */
           _INT_SCALAR    ,  /* istatimg        */
           _INT_ARRAY     ,  /* vdw_typfrag     */
           _DOUBLE_ARRAY  ,  /* occ_orig        */
           _INT_SCALAR    ,  /* irdscr          */
           _INT_SCALAR    ,  /* getgam_eig2nkq  */
           _INT_SCALAR    ,  /* usepaw          */
           _INT_SCALAR    ,  /* use_slk         */
           _DOUBLE_SCALAR ,  /* rcut            */
           _INT_SCALAR    ,  /* pawsushat       */
           _DOUBLE_SCALAR ,  /* diemixmag       */
           _INT_SCALAR    ,  /* nsym            */
           _DOUBLE_SCALAR ,  /* cd_max_freq     */
           _INT_SCALAR    ,  /* cd_use_tangrid  */
           _INT_SCALAR    ,  /* irandom         */
           _INT_SCALAR    ,  /* rfuser          */
           _DOUBLE_ARRAY  ,  /* dmatpawu        */
           _INT_SCALAR    ,  /* prtfsurf        */
           _INT_SCALAR    ,  /* npband          */
           _INT_SCALAR    ,  /* getbsreso       */
           _INT_SCALAR    ,  /* nfft            */
           _INT_SCALAR    ,  /* rfasr           */
           _INT_SCALAR    ,  /* accesswff       */
           _INT_SCALAR    ,  /* fftgw           */
           _INT_SCALAR    ,  /* prtkden         */
           _INT_SCALAR    ,  /* rfelfd          */
           _INT_SCALAR    ,  /* prtvhxc         */
           _INT_SCALAR    ,  /* mgfft           */
           _INT_SCALAR    ,  /* dmatudiag       */
           _INT_SCALAR    ,  /* nbandsus        */
           _INT_SCALAR    ,  /* recgratio       */
           _INT_SCALAR    ,  /* iprctfvw        */
           _INT_SCALAR    ,  /* nshsigx         */
           _INT_SCALAR    ,  /* nshwfn          */
           _DOUBLE_SCALAR ,  /* mdwall          */
           _INT_ARRAY     ,  /* rf1dir          */
           _DOUBLE_SCALAR ,  /* sciss           */
           _INT_SCALAR    ,  /* pawspnorb       */
           _INT_ARRAY     ,  /* rfatpol         */
           _INT_SCALAR    ,  /* npwkss          */
           _DOUBLE_SCALAR ,  /* friction        */
           _INT_SCALAR    ,  /* gw_nqlwl        */
           _INT_SCALAR    ,  /* prtcml          */
           _INT_SCALAR    ,  /* gwcalctyp       */
           _INT_SCALAR    ,  /* bs_hayd_term    */
           _INT_SCALAR    ,  /* irdsuscep       */
           _DOUBLE_ARRAY  ,  /* zeemanfield     */
           _INT_SCALAR    ,  /* chkprim         */
           _INT_ARRAY     ,  /* rf1atpol        */
           _DOUBLE_SCALAR ,  /* dosdeltae       */
           _INT_SCALAR    ,  /* prtefg          */
           _DOUBLE_SCALAR ,  /* kptrlen         */
           _DOUBLE_ARRAY  ,  /* kptgw           */
           _INT_SCALAR    ,  /* bs_coupling     */
           _INT_SCALAR    ,  /* getvel          */
           _INT_SCALAR    ,  /* dmftbandf       */
           _INT_ARRAY     ,  /* bdgw            */
           _INT_SCALAR    ,  /* getpawden       */
           _DOUBLE_SCALAR ,  /* esmear          */
           _INT_SCALAR    ,  /* dmftcheck       */
           _INT_SCALAR    ,  /* prtwf           */
           _DOUBLE_ARRAY  ,  /* wtatcon         */
           _INT_SCALAR    ,  /* nbdblock        */
           _INT_SCALAR    ,  /* gwcomp          */
           _DOUBLE_SCALAR ,  /* wvl_crmult      */
           _INT_SCALAR    ,  /* mqgriddg        */
           _INT_SCALAR    ,  /* bs_nstates      */
           _INT_SCALAR    ,  /* gw_nstep        */
           _DOUBLE_ARRAY  ,  /* efield          */
           _INT_SCALAR    ,  /* tl_nprccg       */
           _DOUBLE_ARRAY  ,  /* bfield          */
           _INT_SCALAR    ,  /* pawprtwf        */
           _DOUBLE_SCALAR ,  /* strfact         */
           _INT_SCALAR    ,  /* ird1wf          */
           _INT_SCALAR    ,  /* rf2phon         */
           _DOUBLE_SCALAR ,  /* nelect          */
           _INT_SCALAR    ,  /* rfddk           */
           _DOUBLE_SCALAR ,  /* dielng          */
           _INT_SCALAR    ,  /* pawprtdos       */
           _DOUBLE_ARRAY  ,  /* jpawu           */
           _INT_SCALAR    ,  /* nqpt            */
           _INT_SCALAR    ,  /* pawlmix         */
           _INT_SCALAR    ,  /* prtlden         */
           _INT_SCALAR    ,  /* optstress       */
           _INT_SCALAR    ,  /* positron        */
           _DOUBLE_SCALAR ,  /* effmass         */
           _INT_ARRAY     ,  /* prtatlist       */
           _INT_SCALAR    ,  /* smdelta         */
           _DOUBLE_SCALAR ,  /* pawujrad        */
           _DOUBLE_ARRAY  ,  /* wtk             */
           _INT_SCALAR    ,  /* getwfk          */
           _DOUBLE_SCALAR ,  /* fixmom          */
           _INT_SCALAR    ,  /* diismemory      */
           _INT_SCALAR    ,  /* getwfq          */
           _DOUBLE_SCALAR ,  /* fband           */
           _INT_SCALAR    ,  /* nbandkss        */
           _DOUBLE_SCALAR ,  /* freqspmax       */
           _INT_SCALAR    ,  /* gw_sigxcore     */
           _INT_SCALAR    ,  /* pitransform     */
           _DOUBLE_SCALAR ,  /* diegap          */
           _DOUBLE_ARRAY  ,  /* ziontypat       */
           _INT_SCALAR    ,  /* pawmixdg        */
           _DOUBLE_SCALAR ,  /* strprecon       */
           _INT_SCALAR    ,  /* prtdipole       */
           _INT_SCALAR    ,  /* istatshft       */
           _INT_SCALAR    ,  /* npweps          */
           _INT_ARRAY     ,  /* rf3dir          */
           _DOUBLE_SCALAR ,  /* spnorbscl       */
           _INT_SCALAR    ,  /* bandpp          */
           _DOUBLE_SCALAR ,  /* omegasimax      */
           _DOUBLE_SCALAR ,  /* ecutwfn         */
           _INT_SCALAR    ,  /* awtr            */
           _INT_SCALAR    ,  /* nkptgw          */
           _INT_SCALAR    ,  /* npulayit        */
           _INT_SCALAR    ,  /* dmft_nwli       */
           _INT_SCALAR    ,  /* rdmnb           */
           _INT_SCALAR    ,  /* rf3phon         */
           _INT_SCALAR    ,  /* nnos            */
           _INT_SCALAR    ,  /* gwrpacorr       */
           _DOUBLE_SCALAR ,  /* dilatmx         */
           _INT_SCALAR    ,  /* dmatpuopt       */
           _DOUBLE_SCALAR ,  /* pawecutdg       */
           _DOUBLE_SCALAR ,  /* tolimg          */
           _INT_SCALAR    ,  /* prtstm          */
           _INT_ARRAY     ,  /* vdw_supercell   */
           _DOUBLE_ARRAY  ,  /* acell_orig      */
           _DOUBLE_SCALAR ,  /* diemac          */
           _INT_SCALAR    ,  /* signperm        */
           _INT_ARRAY     ,  /* rf2dir          */
           _INT_SCALAR    ,  /* irdpawden       */
           _INT_SCALAR    ,  /* prtgden         */
           _INT_SCALAR    ,  /* gw_custom_freqsp */
           _DOUBLE_SCALAR ,  /* soenergy        */
           _INT_SCALAR    ,  /* berryopt        */
           _INT_SCALAR    ,  /* ixcpositron     */
           _INT_SCALAR    ,  /* getqps          */
           _INT_SCALAR    ,  /* timopt          */
           _INT_ARRAY     ,  /* rfdir           */
           _DOUBLE_ARRAY  ,  /* shiftk          */
           _INT_SCALAR    ,  /* cd_custom_imfrqs */
           _INT_ARRAY     ,  /* kberry          */
           _INT_SCALAR    ,  /* bs_loband       */
           _INT_SCALAR    ,  /* mgfftdg         */
           _INT_SCALAR    ,  /* getocc          */
           _INT_SCALAR    ,  /* prtposcar       */
           _INT_SCALAR    ,  /* nomegasrd       */
           _INT_SCALAR    ,  /* iboxcut         */
           _INT_SCALAR    ,  /* iscf            */
           _INT_SCALAR    ,  /* usedmft         */
           _INT_SCALAR    ,  /* nshiftk         */
           _INT_SCALAR    ,  /* prtelf          */
           _INT_SCALAR    ,  /* prtcif          */
           _DOUBLE_SCALAR ,  /* omegasrdmax     */
           _INT_SCALAR    ,  /* natrd           */
           _DOUBLE_SCALAR ,  /* noseinert       */
           _INT_SCALAR    ,  /* intxc           */
           _INT_SCALAR    ,  /* ngroup_rf       */
           _INT_SCALAR    ,  /* spgaxor         */
           _INT_SCALAR    ,  /* get1den         */
           _INT_SCALAR    ,  /* gw_eet          */
           _DOUBLE_SCALAR ,  /* freqsusin       */
           _INT_SCALAR    ,  /* dmftbandi       */
           _INT_SCALAR    ,  /* irdqps          */
           _DOUBLE_ARRAY  ,  /* vel_orig        */
           _INT_SCALAR    ,  /* optnlxccc       */
           _DOUBLE_SCALAR ,  /* diecut          */
           _INT_SCALAR    ,  /* gw_use_pole_scr */
           _INT_SCALAR    ,  /* jellslab        */
           _INT_SCALAR    ,  /* ppmodel         */
           _INT_SCALAR    ,  /* pawoptmix       */
           _INT_SCALAR    ,  /* optcell         */
           _INT_ARRAY     ,  /* scphon_supercell */
           _INT_ARRAY     ,  /* cd_subset_freq  */
           _DOUBLE_SCALAR ,  /* tolwfr          */
           _INT_SCALAR    ,  /* pawfatbnd       */
           _INT_SCALAR    ,  /* prtvolimg       */
           _INT_SCALAR    ,  /* natvshift       */
           _INT_SCALAR    ,  /* gw_sctype       */
           _DOUBLE_ARRAY  ,  /* strtarget       */
           _INT_SCALAR    ,  /* kptopt          */
           _INT_SCALAR    ,  /* w90iniprj       */
           _INT_SCALAR    ,  /* nsppol          */
           _INT_SCALAR    ,  /* nfreqre         */
           _INT_ARRAY     ,  /* supercell       */
           _INT_SCALAR    ,  /* bs_coulomb_term */
           _DOUBLE_ARRAY  ,  /* amu             */
           _INT_SCALAR    ,  /* ptgroupma       */
           _INT_SCALAR    ,  /* pawnhatxc       */
           _DOUBLE_SCALAR ,  /* tphysel         */
           _INT_ARRAY     ,  /* symrel          */
           _INT_SCALAR    ,  /* pawcpxocc       */
           _INT_SCALAR    ,  /* optfreqsus      */
           _DOUBLE_SCALAR ,  /* wvl_frmult      */
           _INT_SCALAR    ,  /* pawusecp        */
           _INT_SCALAR    ,  /* userib          */
           _INT_SCALAR    ,  /* idyson          */
           _INT_ARRAY     ,  /* so_psp          */
           _INT_SCALAR    ,  /* prtpot          */
           _INT_ARRAY     ,  /* istwfk          */
           _INT_SCALAR    ,  /* optforces       */
           _INT_SCALAR    ,  /* brvltt          */
           _DOUBLE_SCALAR ,  /* boxcutmin       */
           _INT_SCALAR    ,  /* ntime           */
           _INT_SCALAR    ,  /* prtvha          */
           _INT_SCALAR    ,  /* npsp            */
           _DOUBLE_SCALAR ,  /* spbroad         */
           _INT_SCALAR    ,  /* symsigma        */
           _DOUBLE_ARRAY  ,  /* goprecprm       */
           _INT_SCALAR    ,  /* prtvol          */
           _INT_SCALAR    ,  /* nqptdm          */
           _INT_SCALAR    ,  /* iprcch          */
           _INT_SCALAR    ,  /* prtbltztrp      */
           _INT_SCALAR    ,  /* isecur          */
           _DOUBLE_SCALAR ,  /* rhoqpmix        */
           _INT_SCALAR    ,  /* natsph          */
           _INT_SCALAR    ,  /* getbscoup       */
           _INT_SCALAR    ,  /* getddk          */
           _INT_SCALAR    ,  /* nwfshist        */
           _DOUBLE_SCALAR ,  /* freqspmin       */
           _DOUBLE_SCALAR ,  /* ecut            */
           _INT_SCALAR    ,  /* pawprt_k        */
           _INT_SCALAR    ,  /* nkpt            */
           _INT_ARRAY     ,  /* symafm          */
           _INT_SCALAR    ,  /* pawprt_b        */
           _INT_SCALAR    ,  /* dmft_dc         */
           _DOUBLE_ARRAY  ,  /* rprim_orig      */
           _INT_SCALAR    ,  /* vdw_xc          */
           _INT_SCALAR    ,  /* ieig2rf         */
           _INT_ARRAY     ,  /* rf2atpol        */
           _INT_SCALAR    ,  /* gw_eet_inclvkb  */
           _DOUBLE_ARRAY  ,  /* bs_eh_cutoff    */
           _DOUBLE_SCALAR ,  /* gw_eet_scale    */
           _INT_SCALAR    ,  /* getsuscep       */
           _INT_SCALAR    ,  /* icutcoul        */
           _INT_SCALAR    ,  /* prtspcur        */
           _INT_SCALAR    ,  /* natom           */
           _INT_SCALAR    ,  /* prtdos          */
           _INT_SCALAR    ,  /* spgorig         */
           _DOUBLE_SCALAR ,  /* recrcut         */
           _INT_SCALAR    ,  /* nspden          */
           _DOUBLE_ARRAY  ,  /* spinat          */
           _INT_SCALAR    ,  /* symmorphi       */
           _DOUBLE_SCALAR ,  /* fermie_nest     */
           _DOUBLE_ARRAY  ,  /* bs_haydock_tol  */
           _INT_SCALAR    ,  /* npspalch        */
           _INT_SCALAR    ,  /* prtnabla        */
           _DOUBLE_ARRAY  ,  /* znucl           */
           _INT_SCALAR    ,  /* gethaydock      */
           _INT_SCALAR    ,  /* pawnzlm         */
           _INT_SCALAR    ,  /* nfreqim         */
           _INT_SCALAR    ,  /* dmft_nwlo       */
           _DOUBLE_ARRAY  ,  /* upawu           */
           _INT_SCALAR    ,  /* prtwant         */
           _INT_SCALAR    ,  /* mband           */
           _INT_SCALAR    ,  /* getscr          */
           _INT_SCALAR    ,  /* optdriver       */
           _INT_SCALAR    ,  /* prtbbb          */
           _INT_ARRAY     ,  /* lexexch         */
           _DOUBLE_SCALAR ,  /* dtion           */
           _INT_SCALAR    ,  /* goprecon        */
           _INT_SCALAR    ,  /* prtgkk          */
           _DOUBLE_ARRAY  ,  /* quadmom         */
           _INT_SCALAR    ,  /* pawprtvol       */
           _DOUBLE_SCALAR ,  /* tolvrs          */
           _INT_SCALAR    ,  /* pawnphi         */
           _INT_SCALAR    ,  /* recnrec         */
           _DOUBLE_SCALAR ,  /* tsmear          */
           _DOUBLE_SCALAR ,  /* tl_radius       */
           _INT_SCALAR    ,  /* cd_full_grid    */
           _INT_SCALAR    ,  /* bs_calctype     */
           _INT_SCALAR    ,  /* posnstep        */
           _DOUBLE_ARRAY  ,  /* qptn            */
           _INT_SCALAR    ,  /* irdhaydock      */
           _DOUBLE_SCALAR ,  /* fxcartfactor    */
           _INT_SCALAR    ,  /* recnpath        */
           _DOUBLE_SCALAR ,  /* elph2_imagden   */
           _DOUBLE_SCALAR ,  /* eshift          */
           _INT_SCALAR    ,  /* gw_npoles       */
           _INT_SCALAR    ,  /* istatr          */
           _DOUBLE_SCALAR ,  /* xc_denpos       */
           _INT_SCALAR    ,  /* getkss          */
           _INT_SCALAR    ,  /* nnsclo          */
           _INT_ARRAY     ,  /* lpawu           */
           _INT_SCALAR    ,  /* xclevel         */
           _INT_SCALAR    ,  /* ntyppure        */
           _INT_SCALAR    ,  /* mqgrid          */
           _DOUBLE_SCALAR ,  /* tolrff          */
           _INT_SCALAR    ,  /* prtdensph       */
           _DOUBLE_SCALAR ,  /* slabzend        */
           _DOUBLE_ARRAY  ,  /* pimass          */
           _INT_SCALAR    ,  /* dmft_iter       */
           _INT_SCALAR    ,  /* nconeq          */
           _DOUBLE_SCALAR ,  /* ppmfrq          */
           _INT_SCALAR    ,  /* chkexit         */
           _INT_SCALAR    ,  /* vacnum          */
           _DOUBLE_SCALAR ,  /* toldff          */
           _DOUBLE_SCALAR ,  /* toldfe          */
           _INT_SCALAR    ,  /* ortalg          */
           _DOUBLE_ARRAY  ,  /* vprtrb          */
           _INT_SCALAR    ,  /* fft_opt_lob     */
           _INT_SCALAR    ,  /* mkqmem          */
           _DOUBLE_SCALAR ,  /* stmbias         */
           _INT_SCALAR    ,  /* rf2elfd         */
           _INT_ARRAY     ,  /* ngfft           */
           _OTHER         
};

#endif
